# This file sets up authentication, storage, and functions configuration

project_id = "obiiomoqhpbgaymfphdz"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15
# Enable SSL mode for database connections
ssl_enforcement = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
# Enable Multi-factor Authentication
enable_mfa = true
# Limit session time for added security
session_expiry = 604800 # 7 days
# Add network restrictions (comma-separated list of CIDR blocks)
# Example: allowed_ips = ["123.123.123.123/32", "124.124.124.0/24"]
# Empty for no restrictions (not recommended for production)
allowed_ips = []

[auth.email]
# Changed from enable_signups to enable_confirmations
double_confirm_changes = true
enable_confirmations = true

# Custom SMTP configuration (Replace with your actual SMTP provider details)
[auth.email.custom_smtp]
enabled = true
server = "smtp.example.com"
port = 587
user = "your-smtp-username"
password = "your-smtp-password"
sender_name = "FlashBot"
sender_email = "noreply@yourcompany.com"
# Security settings for SMTP
admin_email = "admin@yourcompany.com"
security = "STARTTLS" # Options: STARTTLS, SSL

[functions.save-whatsapp-config]
verify_jwt = true

[functions.whatsapp-api-proxy]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = true

[functions.claude-chat]
verify_jwt = true

[functions.kv-store-document]
verify_jwt = true

[functions.register-conversation]
verify_jwt = true

[functions.process-temp-documents]
verify_jwt = true

[functions.kv-get-documents-by-chatbot]
verify_jwt = true

[functions.kv-clear-documents-by-chatbot]
verify_jwt = true

[functions.match-documents]
verify_jwt = true

[functions.process-documents]
verify_jwt = true

[functions.widget-config]
verify_jwt = true
