
# This file sets up authentication, storage, and functions configuration

project_id = "obiiomoqhpbgaymfphdz"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
# Changed from enable_signups to enable_confirmations
double_confirm_changes = true
enable_confirmations = false

[[functions]]
name = "save-whatsapp-config"
verify_jwt = true

[[functions]]
name = "whatsapp-api-proxy"
verify_jwt = true

[[functions]]
name = "whatsapp-webhook"
verify_jwt = false

[[functions]]
name = "claude-chat"
verify_jwt = false

[[functions]]
name = "kv-store-document"
verify_jwt = false

[[functions]]
name = "register-conversation"
verify_jwt = false

[[functions]]
name = "process-temp-documents"
verify_jwt = true

[[functions]]
name = "kv-get-documents-by-chatbot"
verify_jwt = false

[[functions]]
name = "kv-clear-documents-by-chatbot"
verify_jwt = false

[[functions]]
name = "match-documents"
verify_jwt = false

[[functions]]
name = "process-documents"
verify_jwt = true

[[functions]]
name = "widget-config"
verify_jwt = false
